"""initial commit

Revision ID: ebf4ec28f92d
Revises:
Create Date: 2023-08-31 17:03:41.949969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# mypy: ignore-errors
# nosec
# flake8: noqa
# fmt: off
# isort: skip_file

# revision identifiers, used by Alembic.
revision: str = 'ebf4ec28f92d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_type', sa.Enum('STARTUP', 'SHUTDOWN', 'OTHER', name='auditeventtype'), nullable=False),
    sa.Column('event_data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditevent')
    sa.Enum(name='auditeventtype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
